# Generated by Django 2.2 on 2020-01-10 03:23

import apps.verification.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(default=apps.verification.models.sending_verification_algorithm, max_length=4)),
                ('valid', models.BooleanField(default=True)),
                ('for_phone', models.CharField(max_length=20)),
            ],
        ),
    ]
